name: "🐛 Bug report"
description: "動作不良・不具合の報告"
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        バグ報告ありがとうございます！既存の Issue / Discussions を検索済みかご確認ください。
  - type: checkboxes
    id: checks
    attributes:
      label: 事前チェック
      options:
        - label: 既存の Issue/PR/Discussions を検索しました
          required: true
        - label: SUPPORT.md を読みました
          required: true
  - type: input
    id: summary
    attributes:
      label: 要約
      description: 1〜2行で簡潔に
      placeholder: 例）CLI の --model 指定時にクラッシュする
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 実行コマンドや入力データなど、最小再現手順
      render: bash
      placeholder: |
        1. ...
        2. ...
        3. 実際の結果: ...
        4. 期待する結果: ...
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: 環境情報
      description: OS / アーキテクチャ / 言語ランタイム / ライブラリ版 / GPU など
      placeholder: |
        OS: Windows 11 / Ubuntu 22.04 / macOS 14
        Python: 3.11.9
        CUDA: 12.4 / cuDNN 9.2 / GPU: RTX 3080
        パッケージ: faster-whisper 1.0.0, numpy 2.0.1 ...
  - type: textarea
    id: logs
    attributes:
      label: ログ/スタックトレース
      description: 可能なら `--verbose` など詳細ログを添付
      render: text
  - type: textarea
    id: extra
    attributes:
      label: 追加情報
      description: スクリーンショット・補足など
