name: python-ci (reusable)

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: false
        default: '["3.10","3.11","3.12"]'
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-version) }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure LICENSE files exist
        shell: bash
        run: |
          set -euo pipefail
          if [[ ! -f LICENSE && ! -f LICENSE.txt && ! -f LICENSE.md ]]; then
            echo "::error file=LICENSE::Missing LICENSE for docs. Add LICENSE (e.g., CC BY 4.0 or MIT)."
            exit 1
          fi
          
          if git ls-files | grep -E '\.(py|ipynb|js|ts|go|rs|java|kt|cpp|c|cc|h|hpp|cs|rb|php|sh|ps1|lua|r|m|swift|scala|dart)$' >/dev/null; then
            if [[ ! -f LICENSE-CODE ]]; then
              echo "::error file=LICENSE-CODE::Missing LICENSE-CODE for code (e.g., MIT or Apache-2.0)."
              exit 1
            fi
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: pip install -U pip wheel
      - run: |
          if [ -f pyproject.toml ]; then
            pip install -e ".[dev]" || true
          fi
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - run: pytest -q
